services:
  structurizr:
    image: structurizr/lite
    ports:
      - "8086:8080"
    volumes:
      - ./docs:/usr/local/structurizr

  bloodpressure:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - bloodpressure:/var/opt/mssql
    ports:
      - "1433:1433"

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085

  patient:
    build:
      context: /var/jenkins_home/workspace/BloodPressurePip/Patient
      dockerfile: patient/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:8081"

  mesurment:
    build:
      context: .
      dockerfile: mesurment/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8082"

  migration_service:
    build:
      context: .
      dockerfile: EFramework/Migrations.Dockerfile
    depends_on:
      bloodpressure:
        condition: service_started

  jenkins_service:
    image: my-jenkins-with-docker  # The custom Jenkins image
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_service:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    networks:
      - jenkins_network
    restart: always

networks:
  jenkins_network:
    driver: bridge

volumes:
  bloodpressure:
  featurehub-h2-data:
  jenkins_service:
    driver: local
